apiVersion: v1
kind: ServiceAccount
metadata:
  name: gdx-admin
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gdx-admin-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: gdx-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io